---
title: "Property Tax Exemption"
author: "Fernando Garcia - Drazzel Feliu"
date: "8/11/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggmap)
library(tidycensus)
library(mapview)
library(sf)
library(leaflet)
library(viridis)
library(maps)
library(htmlwidgets)
library(htmltools)
library(tigris)
library(reshape2)
library(ggrepel)
library(ggmap)
```

Below, I pull the median property value for year 2018 by tract:  

```{r, warning=FALSE, error=FALSE}
census_data <- get_acs(
  geography = "tract",
  variables = c(
    median_value = "B25077_001"
  ),
  state = "IL",
  county = "Cook County",
  year = 2018,
  geometry = TRUE
)
```

```{r, warning=FALSE, error=FALSE}
census_data <- census_data %>%
  select(GEOID, NAME, estimate, geometry)

census_data <- census_data %>%
  rename(value_18 = estimate)
```


Below, I pull the median property value for year 2013 by tract:  


```{r, warning=FALSE, error=FALSE}
census_data_13 <- get_acs(
  geography = "tract",
  variables = c(
    median_value = "B25077_001"
  ),
  state = "IL",
  county = "Cook County",
  year = 2013,
  geometry = TRUE
)
```

```{r, warning=FALSE, error=FALSE}
census_data_13 <- census_data_13 %>%
  select(GEOID, NAME, estimate, geometry)

census_data_13 <- census_data_13 %>%
  rename(value_13 = estimate)
```

```{r, warning=FALSE, error=FALSE}
st_geometry(census_data_13) <- NULL

census <- census_data %>%
  left_join(census_data_13, by = c("GEOID", "NAME"))
```

```{r, warning=FALSE, error=FALSE}
census <- census %>%
  mutate(increase_value = (value_18 / value_13 - 1) * 100)
```

```{r, warning=FALSE, error=FALSE}
mapview(census, zcol = "increase_value")
```

```{r, warning=FALSE, error=FALSE}
census %>%
  arrange(desc(increase_value)) %>%
  head(5)
```


#Restricting to City of Chicago

```{r, warning=FALSE, error=FALSE}

cityboundary <- read_sf("geo_export_72cf3d72-fa82-4448-a382-c9dd6dcb4fd2.shp")

cityboundary <- st_union(cityboundary)

cityboundary <- st_transform(
  cityboundary,
  4326
)
```

```{r, warning=FALSE, error=FALSE}

class(census)

class(cityboundary)

cityboundary <- st_transform(cityboundary, "+proj=longlat +datum=NAD83 +no_defs")
census <- st_transform(census, "+proj=longlat +datum=NAD83 +no_defs")
```

We do the intersection of both areas:

```{r}
census$inter <- as.numeric(st_intersects(census, cityboundary))

census <- census %>% filter(inter == 1)
```

Filter the areas where the city of Chicago and the cencus tract intersect but not coincide completely:

```{r}

filter_list <- c(
  "17031810000", "17031810200", "17031810301", "17031807600", "17031808002",
  "17031808001", "17031807900", "17031807800", "17031808100", "17031808100",
  "17031805402", "17031805502", "17031810400", "17031805702", "17031770700",
  "17031770602", "17031770500", "17031770800", "17031811600", "17031811701",
  "17031811500", "17031770902", "17031770901", "17031810501", "17031810502",
  "17031810600", "17031811200", "17031811100", "17031810800", "17031810701",
  "17031810702", "17031810900", "17031811900", "17031812200", "17031812100",
  "17031812500", "17031812600", "17031813000", "17031813100", "17031813500",
  "17031813400", "17031813301", "17031813302", "17031813801", "17031814200",
  "17031820700", "17031820800", "17031820300", "17031820400", "17031820502",
  "17031820901", "17031820902", "17031821102", "17031822101", "17031822000",
  "17031821600", "17031821700", "17031821900", "17031822701", "17031822702",
  "17031822802", "17031822801", "17031823200", "17031823303", "17031823304",
  "17031823400", "17031823500", "17031821200", "17031821401", "17031821402",
  "17031821500", "17031826500", "17031826401", "17031825801", "17031825700",
  "17031805600"
)

census <- census %>%
  filter(!GEOID %in% filter_list)
```

Checking the limits:

```{r, warning=FALSE, error=FALSE}

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(data = st_geometry(census))
```

Map #1

```{r, warning=FALSE, error=FALSE}

mapview(census, zcol = "increase_value")

```

Map #2

```{r, warning=FALSE, error=FALSE}
ggplot() +
  geom_sf(census,
    mapping = aes(
      fill = increase_value,
      color = increase_value
    ),
    inherit.aes = F,
    alpha = .99
  ) +
  scale_fill_viridis() +
  scale_color_viridis() +
  theme_minimal() +
  ggtitle("Percentage increase in property houses between 2018 and 2013", )
```

Colors:

```{r}

# calabels <- sprintf(
# paste0("<strong>%g%%</strong> of single filers earning over $200K in Illinois reside in <strong>%s.</strong><br/>"),
#  round(test$x_200_k_or_more_as_pct,2),
# test$county) %>%
# lapply(HTML)

# callaboptions <- labelOptions(
# style = list("font-weight" = "normal",
#             padding = "3px 8px"),
# textsize = "15px",
# direction = "auto")
```

```{r, warning=FALSE, error=FALSE}

color_200k <- colorNumeric(
  palette = c("white", "blue"),
  domain = chicago_only$increase_value
)
```

Map #3:


```{r}

map <- leaflet(options = leafletOptions(zoomSnap = 0.1)) %>%
  addTiles() %>%
  addPolygons(
    data = st_geometry(census),
    color = "black",
    fillColor = color_200k(census$increase_value),
    weight = 2.5,
    fillOpacity = .55,
    smoothFactor = .2
  ) %>%
  addLegend(
    title = "Percentage increase of housing values between 2018 and 2013",
    pal = color_200k,
    values = census$increase_value,
    position = "topright"
  )
saveWidget(map, "downstate_200k.html")

map
```
