---
title: "race"
author: "Fernando Garcia"
date: "8/12/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(ggmap)
library(tidycensus)
library(mapview)
library(sf)
library(leaflet)
library(viridis)
library(maps)
library(htmlwidgets)
library(htmltools)
library(tigris)
library(reshape2)
library(ggrepel)
library(ggmap)
```


```{r message=FALSE, warning=FALSE}
codebook <- load_variables(2017,"acs5")

racecodebook <- codebook %>% filter(str_detect(label,"race")) %>% filter(str_detect(label,"Population of one")) %>%
  mutate(names="name", count=1:7, merge=paste(names,count, sep="")) %>% select(-c(names,count))

```

```{r message=FALSE, warning=FALSE}
racedataindi <- get_acs(geography = "tract",
        variables = unlist(racecodebook$name),
        state = "IL",
        county = "Cook County",
        geometry = T,
        year = 2018,
        cb = FALSE)
```

```{r message=FALSE, warning=FALSE}

racedata <- racedataindi %>% 
  filter(variable!="C02003_002") %>% 
  group_by(GEOID) %>% 
  mutate(sum=sum(estimate)) %>%
  mutate(percent=estimate/sum(estimate)*100)

racedata <- merge(racedata,racecodebook[c(1,2)],by.x="variable",by.y="name") %>% select(-variable) %>%
  mutate(label=str_remove(label,"Estimate!!Total!!Population of one race!!")) %>%   group_by(GEOID) %>% 
  arrange(GEOID)

racedata <- racedata %>%
  select(-c(moe,estimate,sum)) %>%
  mutate(percent=replace_na(percent,0)) %>%
  spread(label,percent) %>% arrange(GEOID)

```

```{r message=FALSE, warning=FALSE}
racedataindi_13 <- get_acs(geography = "tract",
        variables = unlist(racecodebook$name),
        state = "IL",
        county = "Cook County",
        geometry = T,
        year = 2013,
        cb = FALSE)
```

```{r message=FALSE, warning=FALSE}

racedata_13 <- racedataindi_13 %>% 
  filter(variable!="C02003_002") %>% 
  group_by(GEOID) %>% 
  mutate(sum=sum(estimate)) %>%
  mutate(percent=estimate/sum(estimate)*100)

racedata_13 <- merge(racedata_13,racecodebook[c(1,2)],by.x="variable",by.y="name") %>% select(-variable) %>%
  mutate(label=str_remove(label,"Estimate!!Total!!Population of one race!!")) %>%   group_by(GEOID) %>% 
  arrange(GEOID)

racedata_13 <- racedata_13 %>%
  select(-c(moe,estimate,sum)) %>%
  mutate(percent=replace_na(percent,0)) %>%
  spread(label,percent) %>% arrange(GEOID)

```

#Restricting to City of Chicago

```{r, warning=FALSE, error=FALSE}

cityboundary <- read_sf("geo_export_72cf3d72-fa82-4448-a382-c9dd6dcb4fd2.shp")

cityboundary <- st_union(cityboundary)

cityboundary <- st_transform(
  cityboundary,
  4326
)
```

```{r, warning=FALSE, error=FALSE}

class(racedata)

class(racedata_13)

class(cityboundary)

cityboundary <- st_transform(cityboundary, "+proj=longlat +datum=NAD83 +no_defs")

racedata <- st_transform(racedata, "+proj=longlat +datum=NAD83 +no_defs")

racedata_13 <- st_transform(racedata_13, "+proj=longlat +datum=NAD83 +no_defs")
```

We do the intersection of both areas:

```{r}
racedata$inter <- as.numeric(st_intersects(racedata, cityboundary))

racedata_13$inter <- as.numeric(st_intersects(racedata_13, cityboundary))

racedata <- racedata %>% 
  filter(inter == 1)

racedata_13 <- racedata_13 %>% 
  filter(inter == 1)
```

Filter the areas where the city of Chicago and the cencus tract intersect but not coincide completely:

```{r}

filter_list <- c(
  "17031810000", "17031810200", "17031810301", "17031807600", "17031808002",
  "17031808001", "17031807900", "17031807800", "17031808100", "17031808100",
  "17031805402", "17031805502", "17031810400", "17031805702", "17031770700",
  "17031770602", "17031770500", "17031770800", "17031811600", "17031811701",
  "17031811500", "17031770902", "17031770901", "17031810501", "17031810502",
  "17031810600", "17031811200", "17031811100", "17031810800", "17031810701",
  "17031810702", "17031810900", "17031811900", "17031812200", "17031812100",
  "17031812500", "17031812600", "17031813000", "17031813100", "17031813500",
  "17031813400", "17031813301", "17031813302", "17031813801", "17031814200",
  "17031820700", "17031820800", "17031820300", "17031820400", "17031820502",
  "17031820901", "17031820902", "17031821102", "17031822101", "17031822000",
  "17031821600", "17031821700", "17031821900", "17031822701", "17031822702",
  "17031822802", "17031822801", "17031823200", "17031823303", "17031823304",
  "17031823400", "17031823500", "17031821200", "17031821401", "17031821402",
  "17031821500", "17031826500", "17031826401", "17031825801", "17031825700",
  "17031805600"
)

racedata <- racedata %>%
  filter(!GEOID %in% filter_list)

racedata_13 <- racedata_13 %>%
  filter(!GEOID %in% filter_list)
```

Checking the limits:

```{r, warning=FALSE, error=FALSE}

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(data = st_geometry(census))
```

Map #1

```{r message=FALSE, warning=FALSE}

mapview(racedata_13, zcol = "Black or African American")

```


```