---
title: "Untitled"
author: "Drazzel Feliu"
date: "8/31/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(tidyverse)
library(sf)
library(viridis)
library(leaflet)
library(htmlwidgets)
library(tidycensus)
library(htmltools)
library(snakecase)
library(shiny)
library(scales)
options(tigris_use_cache = TRUE)
```

```{r}
gent <- readRDS("gent.RDS")
```


```{r Shiny Map}
shinyApp(ui = bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  absolutePanel(top = 10, right = 10,
                style="z-index:500;",
                numericInput("value_increase",
                             h3("Percentage increase in home values"),
                             min = min(gent$increase_value),
                             max = max(gent$increase_value),
                             value = min(gent$increase_value),
                             step = 1),
                numericInput("income_13",
                             h3("Household income in 2013"),
                             min = min(gent$household_income_13),
                             max = max(gent$household_income_13),
                             value = max(gent$household_income_13),
                             step = 1000),
                numericInput("gentri_3",
                             h3("Change in bachelor degree or higher - Gent 3"),
                             min = min(gent$gentri_3),
                             max = max(gent$gentri_3),
                             value = min(gent$gentri_3),
                             step = 0.01),
                numericInput("gentri_4",
                             h3("Change in White population - Gent 4"),
                             min = min(gent$gentri_4),
                             max = max(gent$gentri_4),
                             value = min(gent$gentri_4),
                             step = 0.01),
                ),
  leafletOutput("map1", width="100%",height="100%" )),

server = function(input, output) {
  output$map1 <- renderLeaflet({
    mapfile <- gent %>%
      filter(increase_value >= input$value_increase,
             income_13 <= input$income_13,
             gentri_3 >= input$gentri_3,
             gentri_4 >= input$gentri_4)
leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(data=st_geometry(mapfile),
              color= "black",
              weight=1.1,
              fillColor = ifelse(mapfile$value_13>221900,"blue","red"),
              smoothFactor = .4,
              fillOpacity = .65) %>%
  addPolygons(
    data = st_geometry(community),
    group = "Community Areas")
  })
})
```

